services:
  - type: web
    name: goatcounter
    env: image
    image:
      url: docker.io/arp242/goatcounter
    envVars:
      - key: GOATCOUNTER_DB
        fromDatabase:
          name: goatcounter-postgres
          property: connectionString

databases:
  - name: goatcounter-postgres
    databaseName: goatcounter
    user: goatcounter
