services:
  - type: web
    name: goatcounter
    env: image
    image:
      url: docker.io/arp242/goatcounter
    envVars:
      - key: PGHOST
        fromDatabase:
          name: goatcounter-postgres
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: goatcounter-postgres
          property: database
      - key: PGUSER
        fromDatabase:
          name: goatcounter-postgres
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: goatcounter-postgres
          property: password

databases:
  - name: goatcounter-postgres
    databaseName: goatcounter
    user: goatcounter
